<?php

// Auto generated by wpfluent Installer.

return array(
    'name'         => 'FluentAffiliate Pro',
    'slug'         => 'fluent-affiliate-pro',
    'domain_path'  => '/language',
    'text_domain'  => 'fluent-affiliate-pro',
    'hook_prefix'  => 'fluent_affiliate_pro/',
    'rest_version' => 'v2',
    'env'          => 'dev',
);
